'use client';
import Image from 'next/image';
import {useCallback,useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {AnimatePresence,motion,useReducedMotion,useScroll,useTransform} from 'framer-motion';
import {ArrowDown,ArrowLeft,ArrowRight,CalendarDays,Check,Copy,Gift,Camera as Instagram,MapPin,Menu,Volume2,VolumeX,X,Wine,Circle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
import {weddingData as d,type Wish,type RSVPInput} from '../weddingData';
import {MotionFrame,OpeningTransition} from '@/components/wedding/entrance';
import {WeddingHero} from '@/components/wedding/hero';
import './entrance.css';
const ease=[0.22,1,0.36,1] as const;
const dateFormat=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'});

function Photo({src,alt,className='',priority=false,position='center',sizes='(min-width:1024px) 50vw, 100vw'}:{src:string;alt:string;className?:string;priority?:boolean;position?:string;sizes?:string}){
 return <picture><source type="image/webp" srcSet={`${src.replace('.webp','-small.webp')} 512w, ${src} 1024w`} sizes={sizes}/><Image unoptimized src={src} alt={alt} fill priority={priority} loading={priority?'eager':'lazy'} sizes={sizes} className={className} style={{objectFit:'cover',objectPosition:position}}/></picture>;
}
function Reveal({children,className='',delay=0}:{children:ReactNode;className?:string;delay?:number}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:32,filter:'blur(6px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,amount:0.12}} transition={{duration:0.8,ease,delay}}>{children}</motion.div>;}
function Monogram(){return <span className="monogram" aria-label="Rani dan Arief"><span>{d.names.bride[0]}</span><i/><span>{d.names.groom[0]}</span></span>;}
function Ornament({line=false}:{line?:boolean}){const reduced=useReducedMotion();return <div className={`ornament ${line?'ornament-line':''}`} aria-hidden="true"><svg viewBox="0 0 80 80" fill="none"><motion.path d="M40 8 51 29 72 40 51 51 40 72 29 51 8 40 29 29Z M40 21 49 40 40 59 31 40Z M21 40 40 31 59 40 40 49Z M40 8V21 M72 40H59 M40 72V59 M8 40H21" stroke="currentColor" strokeWidth="1.2" initial={reduced?false:{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:1.8,ease}}/></svg></div>;}
function Heading({label,children}:{label?:string;children:ReactNode}){return <Reveal className="section-heading">{label&&<p className="eyebrow">{label}</p>}<h2>{children}</h2></Reveal>;}
function MusicPlayer({playing,onToggle}:{playing:boolean;onToggle:()=>void}){return <button className={`icon-button music-button ${playing?'is-playing':''}`} onClick={onToggle} aria-label={playing?'Matikan musik':'Putar musik'} aria-pressed={playing}>{playing?<Volume2 size={19}/>:<VolumeX size={19}/>}</button>;}
function ReadingProgress(){const {scrollYProgress}=useScroll();return <motion.div className="reading-progress" style={{scaleX:scrollYProgress}} aria-hidden="true"/>;}

function Navigation({opened,onOpen,music,toggleMusic}:{opened:boolean;onOpen:(target?:string)=>void;music:boolean;toggleMusic:()=>void}){
 const [menu,setMenu]=useState(false);const [dark,setDark]=useState(true);const reduced=useReducedMotion();
 useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const section=[...document.querySelectorAll<HTMLElement>('[data-tone]')].reverse().find(s=>{const r=s.getBoundingClientRect();return r.top<=50&&r.bottom>50;});if(section)setDark(section.dataset.tone==='dark');});};update();window.addEventListener('scroll',update,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);};},[opened]);
 const navigate=(id:string)=>{setMenu(false);if(!opened)onOpen(id);else setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:reduced?'auto':'smooth'}),80);};
 return <><header className={`navigation ${dark?'on-dark':'on-light'}`}><a href={opened?'#home':'#cover'} aria-label="Kembali ke awal"><Monogram/></a><div className="nav-actions"><MusicPlayer playing={music} onToggle={toggleMusic}/><button className="icon-button" aria-label="Buka menu navigasi" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu size={24} strokeWidth={1.4}/></button></div></header><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="full-dialog menu-overlay" showCloseButton={false}><DialogTitle className="sr-only">Navigasi Undangan</DialogTitle><DialogDescription className="sr-only">Pilih bagian undangan</DialogDescription><div className="overlay-header"><Monogram/><button className="icon-button" aria-label="Tutup menu" onClick={()=>setMenu(false)}><X/></button></div><nav aria-label="Bagian undangan">{d.navigation.map((item,index)=><motion.button key={item.id} initial={reduced?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:index*0.06,duration:0.5,ease}} onClick={()=>navigate(item.id)}><span className="menu-number">0{index+1}</span>{item.label}<ArrowRight size={22}/></motion.button>)}</nav><p className="eyebrow">{d.dateLabel} · {d.city}</p></DialogContent></Dialog></>;
}
function OpeningCover({onOpen,opening,guest}:{onOpen:()=>void;opening:boolean;guest:string}){return <section id="cover" data-tone="dark" className={`opening-cover ${opening?'opening':''}`}><div className="cover-photo"><Photo src={d.images.cover} alt={d.gallery[0].alt} priority sizes="100vw" position="center 24%"/></div><div className="cover-gradient"/><div className="cover-sheen" aria-hidden="true"/><div className="cover-frame" aria-hidden="true"><span className="frame-inner"/><i className="frame-glint"/></div><div className="curtain curtain-left"/><div className="curtain curtain-right"/><div className="cover-copy"><p className="eyebrow">THE WEDDING OF</p><h1><span>{d.names.bride}</span><span><em>&</em> {d.names.groom}</span></h1><p className="eyebrow cover-date">{d.dateLabel}</p><Ornament line/><div className="guest-greeting"><span>Kepada Yth.</span><span>Bapak/Ibu/Saudara/i</span><strong>{guest}</strong></div><button className="cta" onClick={onOpen} disabled={opening}>{opening?'Membuka undangan…':'Buka Undangan'}<ArrowRight size={18}/></button><p className="cover-quote">“Dua jiwa, satu perjalanan,<br/>menuju selamanya.”</p></div><span className="cover-side-note eyebrow">AN INTIMATE CELEBRATION · Pemalang</span></section>;}
function WeddingVerse(){return <section id="doa" data-tone="light" className="verse-section light-section subtle-pattern"><div className="verse-copy"><Reveal><Ornament/><h2>{d.verse.title}</h2><p lang="ar" dir="rtl" className="arabic">{d.verse.arabic}</p><p className="verse-translation">“{d.verse.translation}”</p><p className="verse-source">{d.verse.source}</p><Ornament line/></Reveal></div><div className="temple-fade" aria-hidden="true"><Photo src={d.images.closing} alt="" position="center top"/></div></section>;}
function BrideGroom(){return <section id="mempelai" data-tone="light" className="couple-section light-section"><div className="container"><Heading label="DENGAN RESTU KEDUA ORANG TUA">Dua Hati, Satu Cerita</Heading><div className="profiles">{d.profiles.map((person,i)=><Reveal key={person.name} className="profile" delay={i*0.08}><p className="profile-role eyebrow">{i===0?'THE BRIDE':'THE GROOM'}</p><div className="profile-portrait"><div className="arched-photo"><Photo src={person.photo} alt={person.alt} position="center 32%" sizes="(min-width:1024px) 360px,70vw"/></div><MotionFrame/></div><h3>{person.name}</h3><p>{person.relation}<br/>{person.parents}</p><a className="instagram-link" href={`https://www.instagram.com/${person.instagram}/`} target="_blank" rel="noopener noreferrer"><Instagram size={17} strokeWidth={1.5}/>@{person.instagram}</a>{i===0&&<div className="profile-divider"><span className="signature" aria-hidden="true">&</span></div>}</Reveal>)}</div></div></section>;}
function WeddingEvent(){return <section id="acara" data-tone="dark" className="event-section dark-section"><div className="event-backdrop"><Photo src={d.images.closing} alt="" position="center 15%"/></div><div className="container"><Heading label="SAVE THE DATE">Acara Pernikahan</Heading><div className="event-cards">{d.events.map((event,i)=><Reveal key={event.title} className="event-panel" delay={i*0.1}><div className="event-icon" aria-hidden="true">{i===0?<><Circle/><Circle/></>:<Wine size={34} strokeWidth={1}/>}</div><h3>{event.title}</h3><div className="event-details"><CalendarDays size={20}/><p>{d.fullDate}<br/>{event.time}</p></div><div className="event-details"><MapPin size={20}/><p>{d.venue}<br/>{d.city}</p></div><a className="cta" href={d.mapUrl} target="_blank" rel="noopener noreferrer">Lihat Lokasi<ArrowRight size={18}/></a></Reveal>)}</div><Ornament line/></div></section>;}
function LoveStory(){const ref=useRef<HTMLDivElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start 78%','end 62%']});return <section id="story" data-tone="light" className="story-section light-section"><div className="container"><Heading label="PERJALANAN KAMI">Our Love Story</Heading><Reveal><p className="story-intro">Dari pertemuan sederhana hingga hari ini, setiap bab membawa kami lebih dekat.</p></Reveal><div className="story-modern" ref={ref}><div className="story-progress" aria-hidden="true"><motion.span style={{scaleX:reduced?1:scrollYProgress}}/></div>{d.stories.map((story,i)=><Reveal key={story.year} className={`story-card story-card-${i}`} delay={i*0.06}><div className="story-card-visual"><Photo src={story.photo} alt={story.title} sizes="(min-width:1024px) 26vw, 88vw"/><span className="story-card-index">0{i+1}</span><span className="story-card-year">{story.year}</span></div><div className="story-card-info"><span className="eyebrow">{story.year}</span><h3>{story.title}</h3><p>{story.text}</p><span className="story-card-line" aria-hidden="true"/></div></Reveal>)}</div><Reveal><p className="signature story-signature">Different Chapter,<br/>Same Love.</p></Reveal></div></section>;}

function Gallery(){const [expanded,setExpanded]=useState(false);const [selected,setSelected]=useState<string|null>(null);const swipe=useRef(0);const photos=d.gallery;const displayed=expanded?photos:photos.slice(0,6);const index=photos.findIndex(p=>p.id===selected);const current=photos[index];const next=(direction:number)=>setSelected(photos[(index+direction+photos.length)%photos.length].id);const reduced=useReducedMotion();return <section id="galeri" data-tone="light" className="gallery-section light-section"><div className="container"><Heading label="MOMEN YANG KAMI SIMPAN">Galeri Kami</Heading><Reveal><p className="gallery-intro">Satu koleksi untuk semua cerita — potret yang kami simpan, dari yang paling tenang hingga yang paling meriah.</p></Reveal><motion.div layout={!reduced} className="gallery-mosaic">{displayed.map((photo,i)=><motion.button layout={!reduced} key={photo.id} className={`gallery-photo gallery-photo-${i}`} aria-label={`Lihat foto: ${photo.alt}`} onClick={()=>setSelected(photo.id)} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:0.5,delay:i*0.04}}><motion.div layoutId={reduced?undefined:`photo-${photo.id}`} className="photo-fill"><Photo src={photo.src} alt={photo.alt} position={photo.position} sizes="(min-width:1024px) 33vw,50vw"/></motion.div><span className="photo-vignette"/><span className="gallery-caption"><span>0{i+1}</span><strong>{photo.alt}</strong></span><span className="photo-expand"><ArrowRight size={18}/></span></motion.button>)}</motion.div>{!expanded&&photos.length>6&&<button className="cta" onClick={()=>setExpanded(true)}>Lihat Semua Foto<ArrowRight size={18}/></button>}<Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="full-dialog lightbox" showCloseButton={false} onKeyDown={e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1);}}><DialogTitle className="sr-only">Galeri Foto Rani dan Arief</DialogTitle><DialogDescription className="sr-only">Geser atau gunakan tombol panah untuk melihat foto berikutnya.</DialogDescription><div className="lightbox-top"><span className="eyebrow">{index+1} / {photos.length}</span><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Tutup foto"><X/></button></div>{current&&<motion.div key={current.id} layoutId={reduced?undefined:`photo-${current.id}`} className="lightbox-photo" onTouchStart={e=>{swipe.current=e.touches[0].clientX;}} onTouchEnd={e=>{const distance=e.changedTouches[0].clientX-swipe.current;if(Math.abs(distance)>45)next(distance<0?1:-1);}}><Photo src={current.src} alt={current.alt} className="lightbox-image" sizes="100vw"/></motion.div>}<div className="lightbox-bottom"><button className="icon-button" onClick={()=>next(-1)} aria-label="Foto sebelumnya"><ArrowLeft/></button><p>{current?.alt}</p><button className="icon-button" onClick={()=>next(1)} aria-label="Foto berikutnya"><ArrowRight/></button></div></DialogContent></Dialog></div></section>;}

async function sendRSVP(input:RSVPInput){const response=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const result=await response.json() as {id:string;saved?:boolean;error?:string};if(!response.ok)throw new Error(result.error||'Konfirmasi belum terkirim. Silakan coba lagi.');return result;}
function RSVP({guest,onSaved}:{guest:string;onSaved:()=>void}){
 const [name,setName]=useState('');const [attendance,setAttendance]=useState('');const [guests,setGuests]=useState('');const [message,setMessage]=useState('');const [pending,setPending]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);const key=useRef('');const sending=useRef(false);
 useEffect(()=>{if(guest!==d.guestDefault)setName(guest);},[guest]);
 const submit=useCallback(async(input:RSVPInput)=>{if(sending.current)throw new Error('Konfirmasi sedang dikirim.');sending.current=true;setPending(true);setError('');try{const result=await sendRSVP(input);setSuccess(true);onSaved();toast.success(d.rsvp.success);return result;}catch(err){setError(err instanceof Error?err.message:'Koneksi bermasalah. Silakan coba lagi.');throw err;}finally{sending.current=false;setPending(false);}},[onSaved]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'submit_wedding_rsvp',title:'Konfirmasi kehadiran pernikahan',description:'Mengirim dan menyimpan RSVP. Pesan opsional dipublikasikan di buku tamu. Jalankan setelah tamu menyetujui pengiriman.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:2,maxLength:80},attendance:{type:'string',enum:['hadir','tidak']},guests:{type:'integer',minimum:0,maximum:5},message:{type:'string',maxLength:1000}},required:['name','attendance','guests'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(value:Record<string,unknown>)=>{if(typeof value.name!=='string'||value.name.trim().length<2||!['hadir','tidak'].includes(String(value.attendance))||!Number.isInteger(value.guests)||Number(value.guests)<0||Number(value.guests)>5||(value.attendance==='hadir'&&Number(value.guests)<1))throw new Error('Nama, kehadiran, dan jumlah tamu wajib valid.');const input={id:crypto.randomUUID(),name:value.name.trim(),attendance:value.attendance as 'hadir'|'tidak',guests:value.attendance==='tidak'?0:Number(value.guests),message:typeof value.message==='string'?value.message:''};const result=await submit(input);setName(input.name);setAttendance(input.attendance);setGuests(String(input.guests));setMessage(input.message);return{saved:true,id:result.id};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[submit]);
 const handleSubmit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!attendance||(attendance==='hadir'&&!guests)){setError('Silakan pilih kehadiran dan jumlah tamu.');return;}key.current ||=crypto.randomUUID();try{await submit({id:key.current,name:name.trim(),attendance:attendance as 'hadir'|'tidak',guests:attendance==='hadir'?Number(guests):0,message:message.trim(),website:String(new FormData(event.currentTarget).get('website')||'')});}catch{}};
 return <section id="rsvp" data-tone="light" className="rsvp-section light-section"><div className="narrow"><Heading>{d.rsvp.title}</Heading><Reveal><p className="section-intro">{d.rsvp.description}</p>{success?<div className="rsvp-success" role="status"><span><Check size={32}/></span><h3>Terima kasih, {name}.</h3><p>{d.rsvp.success}</p><a className="text-link" href="#ucapan">Lihat Ucapan & Doa<ArrowDown size={16}/></a></div>:<form onSubmit={handleSubmit} className="rsvp-form"><div className="form-field"><label htmlFor="guest-name">Nama Lengkap</label><input id="guest-name" name="name" autoComplete="name" placeholder="Nama lengkap Anda" value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={80} required/></div><div className="form-field"><label id="attendance-label">Konfirmasi Kehadiran</label><Select value={attendance} onValueChange={setAttendance}><SelectTrigger className="form-select" aria-labelledby="attendance-label"><SelectValue placeholder="Pilih konfirmasi kehadiran"/></SelectTrigger><SelectContent><SelectItem value="hadir">Hadir</SelectItem><SelectItem value="tidak">Tidak Hadir</SelectItem></SelectContent></Select></div><div className="form-field"><label id="guests-label">Jumlah Tamu</label><Select value={attendance==='tidak'?'0':guests} onValueChange={setGuests} disabled={attendance==='tidak'}><SelectTrigger className="form-select" aria-labelledby="guests-label"><SelectValue placeholder="Pilih jumlah tamu"/></SelectTrigger><SelectContent>{attendance==='tidak'&&<SelectItem value="0">0 — Tidak hadir</SelectItem>}{[1,2,3,4,5].map(n=><SelectItem key={n} value={String(n)}>{n} orang</SelectItem>)}</SelectContent></Select></div><div className="form-field"><label htmlFor="guest-message">Pesan atau doa <span>(opsional)</span></label><textarea id="guest-message" placeholder="Tulis pesan untuk kedua mempelai…" value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} rows={4}/></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><p className="form-note">{d.rsvp.privacy}</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="cta full-width" type="submit" disabled={pending}>{pending?'Mengirim…':'Kirim Konfirmasi'}<ArrowRight size={18}/></button></form>}<Ornament/></Reveal></div></section>;
}
function WeddingWishes({revision}:{revision:number}){const [filter,setFilter]=useState('semua');const [wishes,setWishes]=useState<Wish[]>([]);const [loading,setLoading]=useState(true);const [failed,setFailed]=useState(false);const [retry,setRetry]=useState(0);const [hasMore,setHasMore]=useState(false);const [offset,setOffset]=useState(0);useEffect(()=>{setOffset(0);setWishes([]);},[filter,revision]);useEffect(()=>{const abort=new AbortController();setLoading(true);setFailed(false);fetch(`/api/wishes?attendance=${filter}&offset=${offset}`,{signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<{wishes:Wish[];hasMore:boolean}>;}).then(data=>{setWishes(prev=>offset===0?data.wishes:[...prev,...data.wishes]);setHasMore(data.hasMore);}).catch(e=>{if(e.name!=='AbortError')setFailed(true);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[filter,revision,retry,offset]);return <section id="ucapan" data-tone="light" className="wishes-section light-section"><div className="narrow"><Heading>Ucapan & Doa</Heading><Tabs value={filter} onValueChange={setFilter}><TabsList className="category-tabs" aria-label="Filter ucapan">{[['semua','Semua'],['hadir','Hadir'],['tidak','Tidak Hadir']].map(([value,label])=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList>{['semua','hadir','tidak'].map(value=><TabsContent key={value} value={value}><div className="wishes-list" aria-live="polite">{wishes.map(wish=><article className="wish" key={wish.id}><span className="wish-avatar" aria-hidden="true">{wish.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><div className="wish-header"><h3>{wish.name}</h3><span className={`status-badge ${wish.attendance}`}>{wish.attendance==='hadir'?'Hadir':'Tidak Hadir'}</span></div><p>{wish.message}</p><time dateTime={new Date(wish.created_at).toISOString()}>{dateFormat.format(new Date(wish.created_at))}</time></div></article>)}{loading&&<p className="guestbook-state" role="status">Memuat ucapan…</p>}{failed&&<div className="guestbook-state"><p>Ucapan belum dapat dimuat.</p><button className="text-link" onClick={()=>setRetry(v=>v+1)}>Coba lagi</button></div>}{!loading&&!failed&&!wishes.length&&<div className="guestbook-state"><Ornament/><p>{filter==='semua'?'Setiap doa menjadi bagian dari cerita kami.':'Belum ada ucapan untuk pilihan ini.'}</p><small>Jadilah yang pertama menuliskan doa dan harapan.</small></div>}{hasMore&&!loading&&<button className="text-link" onClick={()=>setOffset(v=>v+10)}>Muat ucapan lainnya<ArrowDown size={16}/></button>}</div></TabsContent>)}</Tabs><a className="cta full-width" href="#rsvp" onClick={()=>setTimeout(()=>document.getElementById('guest-message')?.focus({preventScroll:true}),750)}>Tulis Ucapan<ArrowRight size={18}/></a></div></section>;}
function WeddingGift(){const [copied,setCopied]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);const copy=async(number:string)=>{try{await navigator.clipboard.writeText(number);setCopied(number);toast.success('Nomor rekening berhasil disalin.');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(''),2500);}catch{toast.error('Nomor belum tersalin. Tekan dan tahan nomor untuk menyalin.');}};return <section id="gift" data-tone="light" className="gift-section light-section subtle-pattern"><div className="container"><Ornament/><Heading>{d.gift.title}</Heading><Reveal><p className="section-intro gift-intro">{d.gift.description}</p><div className="gift-grid">{d.gift.accounts.map(account=><div className="bank-card" key={account.bank}><div><span className={`bank-logo ${account.bank.toLowerCase()}`}>{account.bank}</span><p className="bank-number">{account.display}</p><p className="account-name">a.n. {account.holder}</p></div><button className={`copy-button ${copied===account.number?'copied':''}`} onClick={()=>copy(account.number)} aria-label={`Salin nomor rekening ${account.bank}`}>{copied===account.number?<Check size={20}/>:<Copy size={20}/>}</button></div>)}<div className="physical-gift"><Gift size={29} strokeWidth={1.3}/><div><h3>Kirim Hadiah Fisik</h3><p>{d.gift.address}</p></div></div></div><Ornament line/></Reveal></div></section>;}
function Closing(){return <section id="closing" data-tone="dark" className="closing-section dark-section"><Photo src={d.images.closing} alt={d.gallery[4].alt} sizes="100vw" position="center 25%"/><div className="closing-gradient"/><div className="closing-copy"><Reveal><h2>{d.closing.title}</h2><p>{d.closing.text}</p><p className="signature">{d.closing.signature}</p><p className="eyebrow">{d.dateLabel}</p><Ornament line/><Monogram/></Reveal></div></section>;}

function useWeddingMusic(){const [playing,setPlaying]=useState(false);const audio=useRef<HTMLAudioElement|null>(null);useEffect(()=>{if(typeof Audio==='undefined')return;const track=new Audio(d.music);track.loop=true;track.preload='metadata';track.volume=.42;const onPlay=()=>setPlaying(true);const onPause=()=>setPlaying(false);const onError=()=>setPlaying(false);track.addEventListener('play',onPlay);track.addEventListener('pause',onPause);track.addEventListener('error',onError);audio.current=track;return()=>{track.pause();track.removeEventListener('play',onPlay);track.removeEventListener('pause',onPause);track.removeEventListener('error',onError);track.src='';audio.current=null;};},[]);const start=useCallback(async(notify=false)=>{const track=audio.current;if(!track){if(notify)toast.error('Musik belum siap.');return;}try{await track.play();setPlaying(true);}catch{if(notify)toast.error(`Tambahkan file musik di public${d.music}.`);}},[]);const stop=useCallback(()=>{audio.current?.pause();setPlaying(false);},[]);return{playing,start,stop};}
export default function WeddingInvitation() {
 const [opened,setOpened]=useState(false);
 const [entering,setEntering]=useState(false);
 const [guest,setGuest]=useState(d.guestDefault);
 const [revision,setRevision]=useState(0);
 const openingRef=useRef(false);
 const reduced=useReducedMotion();
 const music=useWeddingMusic();
 useEffect(()=>{const to=new URLSearchParams(window.location.search).get('to')?.trim().slice(0,100);if(to)setGuest(to);},[]);
 // Lock the document only while the cover or opening panels are present.
 useEffect(()=>{
   if(opened&&!entering)return;
   const previousBody=document.body.style.overflow;
   const previousRoot=document.documentElement.style.overflow;
   document.body.style.overflow='hidden';
   document.documentElement.style.overflow='hidden';
   window.scrollTo({top:0,behavior:'instant'});
   return()=>{document.body.style.overflow=previousBody;document.documentElement.style.overflow=previousRoot;};
 },[opened,entering]);
 const open=(target='home')=>{
   if(opened){document.getElementById(target)?.scrollIntoView({behavior:reduced?'auto':'smooth'});return;}
   if(openingRef.current)return;
   openingRef.current=true;
   window.scrollTo({top:0,behavior:'instant'});
   setEntering(true);
   setOpened(true);
   void music.start();
 };
 useEffect(()=>{if(opened&&!entering)document.getElementById('home')?.focus({preventScroll:true});},[opened,entering]);
 const finishOpening=useCallback(()=>setEntering(false),[]);
 const saved=useCallback(()=>setRevision(v=>v+1),[]);
 return <>
   {!opened&&<a href="#home" className="skip-link" onClick={event=>{event.preventDefault();open();}}>Lewati pembuka</a>}
   <AnimatePresence initial={false}>
     {!opened&&<motion.div key="cover" className="cover-layer" exit={{opacity:0}} transition={{duration:reduced?0:0.3}}>
       <div className="cover-brand"><Monogram/><span className="eyebrow">A WEDDING INVITATION</span></div>
       <OpeningCover onOpen={()=>open()} opening={false} guest={guest}/>
     </motion.div>}
   </AnimatePresence>
   {opened&&<>
     <ReadingProgress/>
     <div inert={entering}><Navigation opened onOpen={open} music={music.playing} toggleMusic={()=>{if(music.playing)music.stop();else void music.start(true);}}/></div>
     <main inert={entering} className="invitation-content is-open">
       <WeddingHero/><WeddingVerse/><BrideGroom/><WeddingEvent/><LoveStory/><Gallery/>
       <div className="response-pair"><RSVP guest={guest} onSaved={saved}/><WeddingWishes revision={revision}/></div>
       <WeddingGift/><Closing/>
     </main>
   </>}
   {entering&&<OpeningTransition onComplete={finishOpening}/>}
   <Toaster position="bottom-center" theme="light" toastOptions={{className:'wedding-toast',duration:3500}}/>
 </>;
}
